name: sample-app-nextjs
services:
- dockerfile_path: Dockerfile
  instance_count: 1
  instance_size_slug: apps-s-1vcpu-0.5gb
  name: sample-dockerfile-nextjs
  github:
    branch: main
    deploy_on_push: true
    repo: bikram20/appplat-nextapp
